# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

 
stages:
  - stage: BuildApp
    displayName: Build Apps

    jobs:
      - job: BuildFrontendApp
        displayName: Build Frontend App

        pool:
          vmImage: ubuntu-latest

        steps:
        - script: echo building frontend app
          displayName: build frontend app
        - script: echo running unit tests for frontend app
          displayName: unit tests frontend

 
      - job: BuildBackendApp
        displayName: Build Backend App
        
        steps:
        - script: echo building backend app
          displayName: build backend app
        - script: echo running unit tests for backend app
          displayName: unit tests backend
